local function apply()
	-- Clear cache so re-requiring picks up newly-generated colors
	package.loaded["noctalia.onedark"] = nil

	-- This file is GENERATED by Noctalia
	local ok, mod = pcall(require, "noctalia.onedark")
	if ok and mod and mod.apply then
		mod.apply()
	end
end

apply()

-- Optional: hot reload when Noctalia post_hook sends SIGUSR1
local signal = vim.uv.new_signal()
signal:start(
	"sigusr1",
	vim.schedule_wrap(function()
		apply()
	end)
)
