alias myip="curl http://ipecho.net/plain; echo"

alias grep='grep -E'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias findfile='sudo find / -iname'
alias findpath='sudo find / -path'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias cl='clear && ls'
alias cll='clear && ll'
alias c='clear'
alias cmake='clear && make'
alias src='source ~/.bashrc'
alias vimalias='vim ~/.bash_aliases'
