#!/bin/bash

if [ ! -d ~/olddots ]; then
	mkdir ~/olddots
fi

cp ~/.bashrc ~/.bash_aliases ~/.vimrc ~/olddots/ #preserve last version of dots
if [ $? -eq 0 ]; then
	cp .bashrc .bash_aliases .vimrc ~/
else
	echo "Could not preserve old dotfiles - exiting without moving new ones."
	return 1
fi
