local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', function() builtin.find_files({ hidden = true }); end, { desc = "[p]roject [f]ind files" })
vim.keymap.set('n', '<C-p>', builtin.git_files, { desc = "Search git project" })
vim.keymap.set('n', '<leader>ps', function() builtin.grep_string({ search = vim.fn.input("🔍 "), hidden = true }); end, { desc = "[p]roject [s]earch string" })
vim.keymap.set('v', '<leader>ps', function() builtin.grep_string(); end, { desc = "[p]roject [s]earch string" })
vim.keymap.set('n', '<leader>gr', function() builtin.live_grep({ hidden = true }); end, { desc = "[g][r]ep" })
vim.keymap.set('n', '<leader>fM', builtin.marks, { desc = "[f]ind [m]ark" })
