color0 #21252b
color1 #e27881
color2 #98c379
color3 #eac786
color4 #71b9f4
color5 #c88bda
color6 #62bac6
color7 #c9ccd3
color8 #282c34
color9 #e68991
color10 #a8cc8e
color11 #edcf97
color12 #8dc7f6
color13 #d3a2e2
color14 #78c4ce
color15 #e6e6e6
background #21252b
selection_foreground #e6e6e6
cursor #78c4ce
cursor_text_color #21252b
foreground #e6e6e6
selection_background #393e47
active_border_color #62bac6
inactive_border_color #eac786

active_tab_foreground   #21252b
active_tab_background   #62bac6
inactive_tab_foreground #78c4ce
inactive_tab_background #282c34
cursor_trail_color      #78c4ce
