-- GENERATED by Noctalia (from onedark-template.lua)
-- Do not edit output directly.

local M = {}

function M.apply()
	require("onedark").setup({
		colors = {
			bg0 = "#1f2329",
			bg1 = "#30363f",
			bg2 = "#39404b",
			bg3 = "#656d7b",
			fg = "#a0a8b7",
			fg_dark = "#8ebd6b",
			fg_light = "#a0a8b7",

			red = "#e55561",
			orange = "#bf68d9",
			yellow = "#61afef",
			green = "#4fa6ed",
			cyan = "#d696e9",
			blue = "#8bc5f3",
			purple = "#8bc4f3",

			comment = "#656d7b",
			dark_red = "#800812",
		},
	})

	require("onedark").load()
end

return M
