-- GENERATED by Noctalia (from onedark-template.lua)
-- Do not edit output directly.

local M = {}

function M.apply()
	require("onedark").setup({
		colors = {
			bg0 = "{{colors.surface.default.hex}}",
			bg1 = "{{colors.surface_container.default.hex}}",
			bg2 = "{{colors.surface_container_high.default.hex}}",
			bg3 = "{{colors.outline.default.hex}}",
			fg = "{{colors.on_surface.default.hex}}",
			fg_dark = "{{colors.on_surface_variant.default.hex}}",
			fg_light = "{{colors.on_background.default.hex}}",

			red = "{{colors.error.default.hex}}",
			orange = "{{colors.tertiary.default.hex}}",
			yellow = "{{colors.secondary.default.hex}}",
			green = "{{colors.primary.default.hex}}",
			cyan = "{{colors.tertiary_fixed_dim.default.hex}}",
			blue = "{{colors.primary_fixed_dim.default.hex}}",
			purple = "{{colors.secondary_fixed_dim.default.hex}}",

			comment = "{{colors.outline.default.hex}}",
			dark_red = "{{colors.error_container.default.hex}}",
		},
	})

	require("onedark").load()
end

return M
